import 'dart:io';

import 'package:sqlite3/sqlite3.dart';

/// Must match the Android `applicationId` set in android/app/build.gradle
/// (generated by `flutter create --platforms=android --org com.jaichand .`,
/// which derives it from this org plus the `name:` in pubspec.yaml).
const String kApplicationId = 'com.jaichand.break_reminder_app';

/// Android's per-app private storage directory is deterministic and does not
/// require any plugin call to resolve, which matters because this path is
/// also used from the headless background isolate that handles a
/// notification-action tap (no Flutter engine / MethodChannels available
/// there, so `path_provider` cannot be used).
String get _breaksDbDir => '/data/user/0/$kApplicationId/app_flutter';

String get breaksDbPath => '$_breaksDbDir/breaks.db';

/// Opens (creating if needed) the breaks database. Safe to call from both
/// the UI isolate and the background notification-response isolate.
Database openBreaksDatabase() {
  Directory(_breaksDbDir).createSync(recursive: true);
  final db = sqlite3.open(breaksDbPath);
  // Both isolates may touch the file around the same time (e.g. a reminder
  // fires while the app happens to be open); WAL lets a reader and a writer
  // proceed concurrently, and the busy timeout covers writer-vs-writer.
  db.execute('PRAGMA journal_mode = WAL;');
  db.execute('PRAGMA busy_timeout = 3000;');
  db.execute('''
    CREATE TABLE IF NOT EXISTS breaks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      start_ts TEXT NOT NULL,
      end_ts TEXT,
      duration_seconds INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL
    )
  ''');
  return db;
}
