import 'dart:io';

import 'package:sqlite3/sqlite3.dart';

/// Must match the Android `applicationId` set in android/app/build.gradle
/// (generated by `flutter create --platforms=android --org com.jaichand .`,
/// which derives it from this org plus the `name:` in pubspec.yaml).
const String kApplicationId = 'com.jaichand.squat_reminder';

/// Android's per-app private storage directory is deterministic and does not
/// require any plugin call to resolve, which matters because this path is
/// also used from the headless background isolate that handles a
/// notification-action tap (no Flutter engine / MethodChannels available
/// there, so `path_provider` cannot be used).
String get _squatsDbDir => '/data/user/0/$kApplicationId/app_flutter';

String get squatsDbPath => '$_squatsDbDir/squats.db';

/// Opens (creating if needed) the squats database. Safe to call from both
/// the UI isolate and the background notification-response isolate.
Database openSquatsDatabase() {
  Directory(_squatsDbDir).createSync(recursive: true);
  final db = sqlite3.open(squatsDbPath);
  // Both isolates may touch the file around the same time (e.g. a reminder
  // fires while the app happens to be open); WAL lets a reader and a writer
  // proceed concurrently, and the busy timeout covers writer-vs-writer.
  db.execute('PRAGMA journal_mode = WAL;');
  db.execute('PRAGMA busy_timeout = 3000;');
  db.execute('''
    CREATE TABLE IF NOT EXISTS squats (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      timestamp TEXT NOT NULL,
      count INTEGER NOT NULL
    )
  ''');
  return db;
}
